### ISSUE TITLE
Glossary of tags

### ISSUE THREAD

**Issue by samarulmeu** [ennioitaliano/obsidian-auto-glossary#16]
Will it be possible to have an index of tags generated? Something like: 

`- tag_name: file1, file2, file3`

Thank you!

**Comment by ennioitaliano** [comment]
I'm not sure I have understand correctly. You want a tag at the beginning of an index/glossary file with a list of the included files?

**Comment by samarulmeu** [comment]
So let's suppose I have files `file1, file2` with the tags `#tag1` and `#tag2` inside, files `file2, file3` with tags `#tag2 #tag3` inside and file `file4` with `#tag1` and `#tag3` inside. I would like to have a glossary file that looks like this:

```
- tag1: file1, file2, file4
- tag2: file2, file3
- tag3: file2, file3, file4
```

**Comment by ennioitaliano** [comment]
Ok, now it's clear but I think this goes out of the scope of this plugin, at least for now. Sorry about that :(
