### ISSUE TITLE
FR: Allow creation based on Dataview Field

### ISSUE THREAD

**Issue by brimwats** [ennioitaliano/obsidian-auto-glossary#3]
Just an idea! I have a lot of "Dates Founded:: ####" in my notes, so I'd love to be able to organize those numerically by dataview field. I would envison you'd have a DV option in a dropdown and then a new row would appear where one would type the field and the value wanted

**Comment by ennioitaliano** [comment]
Hi and thank you for the suggestion!
I have some doubts about your request:
1. I don't recognize the  "Dates Founded:: ####" syntax; in particular, I don't know what "::" means. Is that syntax useful or generated by a plugin or it's just a convention you use?
2. What do you mean by "organize those numerically by dataview field" (or by "the field and the value wanted")? Are you suggesting the possibility to create an index of files with the same value for a certain field or a single file divided in some way by field and respective value?

**Comment by brimwats** [comment]
hmm I think you might not be aware of data view?

https://github.com/blacksmithgu/obsidian-dataview

https://blacksmithgu.github.io/obsidian-dataview/

**Comment by ennioitaliano** [comment]
> hmm I think you might not be aware of data view?
> 
> 
> 
> https://github.com/blacksmithgu/obsidian-dataview
> 
> 
> 
> https://blacksmithgu.github.io/obsidian-dataview/

Yes, I stumbled upon this plugin (that's why I thought that syntax was related to a plugin) but never used it.

I will try to learn something about its usage; I can't promise anything short-term, but maybe someone else will try to implement the feature you asked for!

**Comment by ennioitaliano** [comment]
Ok @brimwats, tell me if I'm right: you want to create an index/glossary of all your notes with a certain value for a certain field? e.g. an index of all the note with a certain value for the field "Dates Founded"

If I understood well, to do this I'll just have to create a file with the right query inside, am I right?

**Comment by brimwats** [comment]
you've got it! I think there was a "dataview builder" website awhile back but I don't have the link currently! will look for it

**Comment by ennioitaliano** [comment]
> you've got it! I think there was a "dataview builder" website awhile back but I don't have the link currently! will look for it

Ok, I took some time thinking about this feature. I think that it does not belong to this project but, like the website you mentioned, it could be a suitable idea for another plugin, so I'm gonna close this issue for now.

By the way, I don't exclude working on a plugin like the one you requested by myself :)
