### ISSUE TITLE
Filenames with a comma are not processed correctly

### ISSUE THREAD

**Issue by profucius** [ennioitaliano/obsidian-auto-glossary#6]
Hi there, great plugin you've developed! I have a small issue and I hope you can help.

Any files that I am creating a glossary of, which contain a comma, your plugin seems to ignore the comma. It still generates the glossary file, and includes all of the other characters in the filename, but just omits the comma. The entry in the glossary file will then say "the file has not yet been created" due to the filename being different without the comma.

Is is something that can be fixed in the code of the plugin? I do depend on having commas in my filenames, and I cannot yet think of a way to workaround this issue.

Unrelated: While I'm here, I'd just like to say that I'd love to see your plugin be capable of auto-updating existing glossaries. I can see myself integrating this into a workflow which greatly improves my use of Obsidian for certain topics, it would improve my productivity greatly if it were to be implemented <3

**Comment by ennioitaliano** [comment]
Hi @profucius, thank you for this bug report.
Unfortunately, at the moment I am taken by university exams and other commitments, so I cannot guarantee that I will solve this problem quickly. This also applies to request #7, but I will work on both these issues as soon as I have time.
