### ISSUE TITLE
Implement a setting to allow overwriting existing glossary file

### ISSUE THREAD

**Issue by profucius** [ennioitaliano/obsidian-auto-glossary#7]
I find myself needing to update glossary files fairly frequently, due to adding new files to a directory which I am using Auto Glossary on. However, if a previous glossary file exists, your plugin will not overwrite it. 

I can understand avoiding overwriting if the user was unaware one existed, and perhaps wanted to keep it instead. But in my use-case, I always want to overwrite an existing glossary file. Would you be willing to add a setting, or a prompt, which allows for overwriting existing glossary/index files? That would be really great.

**Comment by ennioitaliano** [comment]
See comment in bug report #6

**Comment by aikruger** [comment]
This would be a great addition to fantastic tool. Could I added that it would be great to have an option in creating a glossary to automatically update the glossary as new files are added to the folder
